module.exports = {
    USER_JOIN_CHAT: "USER_JOIN_CHAT",
    USER_LEAVE_CHAT: "USER_LEAVE_CHAT",
    USER_UPDATE_CURRENT_INDEX: "USER_UPDATE_CURRENT_INDEX",
    GAME_START: "GAME_START",
    GAME_END: "GAME_END",
    USER_COMPLETED_TEXT: "USER_COMPLETED_TEXT"
}